name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout nodecg/nodecg
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          repository: nodecg/nodecg
          path: ./nodecg-temp

      - name: Copy ./nodecg-temp > ./nodecg
        run: cp -r ./nodecg-temp ./nodecg

      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets['GITHUB_TOKEN'] }}
          ref: ${{ github.ref }}
          fetch-depth: 0
          path: ./nodecg/bundles/ipl-overlay-controls

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up NPM cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Update NPM
        run: npm install -g npm@7.7.0

      - name: Install NPM dependencies
        working-directory: ./nodecg/bundles/ipl-overlay-controls
        run: npm ci

      - name: Run ESLint on source
        working-directory: ./nodecg/bundles/ipl-overlay-controls
        run: npm run lint

      - name: Update build branch
        uses: ./nodecg/bundles/ipl-overlay-controls/.github/actions/update-build-branch
        if: github.ref == 'refs/heads/master'
